# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# poly_to_raster.py
# Created on: 2018-11-05 10:43:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, os, glob, sys


# Arc workspace
arcpy.env.workspace = "D:\\projects\\place\\gis\\data\\test"
outfolder = "D:\\projects\\place\\gis\\data\\tables\\data"

fcs = arcpy.ListFeatureClasses()

# Loop through all fcs
for fc in fcs:
    print(fc)



#rg_ex_monthly_water_2011_02_clip_dissolve_prox
#    shp = os.path.join(shpfolder, "rg_ex_monthly_water_2011_02_clip_dissolve_prox + "_dissolve_prox.shp")
#    shp_out =


# Process: Add Field
#arcpy.AddField_management(rg_ex_monthly_water_2011_03_clip_dissolve_prox_shp, "gridno", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Project
 #   arcpy.Project_management(shp, rg_ex_monthly_water_2011_03_clip_dissolve_prox_proj_shp, "PROJCS['WGS_1984_UTM_Zone_16N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-87.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "NO_PRESERVE_SHAPE", "", "NO_VERTICAL")

# Process: Polygon to Raster
#arcpy.PolygonToRaster_conversion(rg_ex_monthly_water_2011_03_clip_dissolve_prox_proj_shp, "GRIDCODE", grid2011_03b, "CELL_CENTER", "NONE", "30")

