# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# poly_to_raster2.py
# Created on: 2018-11-21 09:18:52.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, os, glob, sys
from arcpy import env


arcpy.CheckOutExtension("Spatial")

# Arc workspace
arcpy.env.workspace = "D:\\projects\\place\\gis\\data\\test\\utm"
outfolder = "D:\\projects\\place\\data\\tables\\test"
huc_shp = "D:\\projects\\place\\gis\\data\\WBDHU8_Central_Valley\\WBDHU8_Central_Valley_UMT10.shp"

fcs = arcpy.ListFeatureClasses()
i = 1
# Loop through all fcs
for fc in fcs:
    i=i+1
    print(fc)
    rastername = "c2011_" + str(i)

# Process: Polygon to Raster
    arcpy.PolygonToRaster_conversion(fc, "FID", rastername, "CELL_CENTER", "NONE", "30")
    print("Converted file " + str(i) + "to raster")

# Process: Tabulate Area
    output_table = os.path.join(outfolder, "zonal_" + str(i))
    print(output_table)
    arcpy.gp.TabulateArea_sa(huc_shp, "HUC8", rastername, "VALUE", output_table, "30")
    print('Tabulated area')

