# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# poly_to_raster_tab_area.py
# Created on: 2018-11-21 09:30:06.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
WBDHU8_Central_Valley_UMT10_shp = "D:\\projects\\place\\gis\\data\\WBDHU8_Central_Valley\\WBDHU8_Central_Valley_UMT10.shp"
rg_ex_monthly_water_2011_02_clip_dissolve_prox = "rg_ex_monthly_water_2011_02_clip_dissolve_prox"
c2011_2b = "D:\\projects\\place\\gis\\data\\rasters\\c2011_2b"
area_2b = os.path.join("D:\\projects

# Process: Polygon to Raster
arcpy.PolygonToRaster_conversion(rg_ex_monthly_water_2011_02_clip_dissolve_prox, "FID", c2011_2b, "CELL_CENTER", "NONE", "30")

# Process: Tabulate Area
arcpy.gp.TabulateArea_sa(WBDHU8_Central_Valley_UMT10_shp, "HUC8", c2011_2b, "VALUE", area_2b, "30")

